### PR TITLE
Add remaining type hints

### PR DESCRIPTION
**Pull request by scop**
...and fix a Descriptor.to_xml bug that was found while doing so.

### CODE REVIEW

**Comment by scop** [comment]
@StevenLooman ping :)

**Comment by StevenLooman** [comment]
Totally forgot about it, sorry. Thank you for pinging.

Looks good to me, merging.

**Comment by StevenLooman** [comment]
I'll release a new version, to be integrated in the next version of `async_upnp_client`.

**Comment by StevenLooman** [comment]
An FYI: I needed to add `didl_lite/py.typed` to make `mypy` understand it should get typing info. To be included in version `1.2.2`.

Also, typing check on  `async_upnp_client` now gives:
```
async_upnp_client/profiles/dlna.py:630: error: "None" not callable
async_upnp_client/profiles/dlna.py:654: error: Item "DidlObject" of "Union[DidlObject, Descriptor]" has no attribute "title"
async_upnp_client/profiles/dlna.py:654: error: Item "Descriptor" of "Union[DidlObject, Descriptor]" has no attribute "title"
async_upnp_client/profiles/dlna.py:677: error: Item "DidlObject" of "Union[DidlObject, Descriptor]" has no attribute "album_art_uri"
async_upnp_client/profiles/dlna.py:677: error: Item "Descriptor" of "Union[DidlObject, Descriptor]" has no attribute "album_art_uri"
async_upnp_client/profiles/dlna.py:679: error: Item "Descriptor" of "Union[DidlObject, Descriptor]" has no attribute "resources"
```

Will fix those later in `async_upnp_client`, and release version `python-didl-lite==1.2.2` when those are fixed.

**Comment by StevenLooman** [comment]
@scop Right now `python-didl-lite` is setting properties dynamically, based on `DidlObject.didl_property_defs` (and its children.) MyPy isn't able to infer the set properties (not surprising.)

Do you have an idea how we could 'inform' MyPy of the properties per object?

**Comment by StevenLooman** [comment]
Overriding __getattr__ with a typed function, as per the [MyPy Python3 cheat sheet](https://github.com/python/mypy/blob/master/docs/source/cheat_sheet_py3.rst#when-youre-puzzled-or-when-things-are-complicated) fixed the issue.

**Pull request merged**
