### PR TITLE
Quirk to allow weirdly-cased upnp:class names

### PR DESCRIPTION
**Pull request by chishm**
This is a workaround for [an issue](https://github.com/home-assistant/core/issues/104556) raised with Home Assistant not being able to connect to the UPNP server on a Digitus NAS box.

There's a few other supporting changes here, split out into separate commits. They're each quite small and self-contained, but I'm happy to put in separate PRs for them if you'd prefer.

### CODE REVIEW

**Comment by StevenLooman** [comment]
Thank you! The changes look good to me. Can you add entries to `CHANGELOG.md` for these?

**Comment by chishm** [comment]
You're welcome. I've updated the `CHANGES.rst` file with the important changes. I've also bumped the version to "1.4.0.dev0" because this PR will cause a change in behaviour, but it should be a non-breaking change.

The version bump will need to be reflected in async_upnp_client and Home Assistant, too. I can put follow-up PRs in when the time comes.

**Comment by StevenLooman** [comment]
I'll create a release for this. I don't expect any further changes soon.

**Comment by StevenLooman** [comment]
I've released [1.4.0](https://pypi.org/project/python-didl-lite/1.4.0/).

**Comment by StevenLooman** [comment]
@chishm Do you also want a release of async-upnp-client?

**Comment by chishm** [comment]
@StevenLooman Thanks for merging, and getting everything properly supported on current Python versions.

Yes please to the release of async-upnp-client, it'll be needed for fixing [hass issue 104556](https://github.com/home-assistant/core/issues/104556).

**Comment by StevenLooman** [comment]
I've released [0.38.0](https://pypi.org/project/async-upnp-client/0.38.0/). During the release of 0.37.0 I forgot to do a `git pull` on my own clone. I've deleted 0.37.0 from [pypi](https://pypi.org/project/async-upnp-client/#history), but I'm not sure if this was the best thing to do.

Perhaps it is time to automate releasing from GitHub Actions.

**Pull request merged**
